Ref to course catogary
andythsu/WaterlooStudies pull request #13
Opened 2021-03-07 03:53 UTC by b46xu

Added a reference link under the course search bar on the Credit Tracker page.

2021-03-07 07:21 UTC, andythsu requested changes

2021-03-07 07:21 UTC, andythsu commented on src/views/CreditTracker.vue
> +				</div>
Why do we need these four lines?

2021-03-07 07:21 UTC, andythsu commented on src/views/CreditTracker.vue
> +
delete these unnecessary blank lines

2021-03-07 07:38 UTC, andythsu requested changes

2021-03-07 07:38 UTC, andythsu commented on src/views/CreditTracker.vue
> +				</div>
```
<div>
<b-form-select>...</b-form-select>
<label style="
    font-size: 12px;
    float: left;
">Please visit {{url}} for more info
</label>
</div>

```
You can change line [#22](https://github.com/andythsu/WaterlooStudies/pull/13/files#diff-b5be0abcfcab0ef1ff76b1776ce91a625d13552c3fff739a12cb136d3e86185fR24) to this to make it display better

2021-03-07 19:28 UTC, b46xu commented
Problems resolved

2021-03-08 14:25 UTC, andythsu requested changes

2021-03-08 14:25 UTC, andythsu commented on package.json
> +		"vue-linkify": "^1.0.1",
we don't need this

2021-03-08 14:25 UTC, andythsu commented on src/views/CreditTracker.vue
> +						">Please visit <a href="https://ugradcalendar.uwaterloo.ca/" class="linkified" target="_blank">https://ugradcalendar.uwaterloo.ca/</a> for more info
we don't need `class=linkified`

2021-03-08 14:25 UTC, andythsu commented on src/views/CreditTracker.vue
> +					float: center;
should be `float:left`

2021-03-25 02:24 UTC, andythsu approved these changes

2021-03-25 02:24 UTC, merged